#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fangfrisch
Version  : 1.2.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/ce/b2/00471c29a21eea66daed2ae3f3eeb58be3cafbd2354adcae379f16b8dc08/fangfrisch-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/b2/00471c29a21eea66daed2ae3f3eeb58be3cafbd2354adcae379f16b8dc08/fangfrisch-1.2.0.tar.gz
Summary  : Update and verify unofficial Clam Anti-Virus signatures
Group    : Development/Tools
License  : GPL-3.0+
Requires: fangfrisch-bin = %{version}-%{release}
Requires: fangfrisch-python = %{version}-%{release}
Requires: fangfrisch-python3 = %{version}-%{release}
Requires: SQLAlchemy
Requires: requests
BuildRequires : SQLAlchemy
BuildRequires : buildreq-distutils3
BuildRequires : requests

%description
==========
Fangfrisch
==========
Fangfrisch (German for "freshly caught") is a sibling of the `Clam Anti-Virus`_ freshclam utility.
It allows downloading virus definition files that are not official ClamAV canon, e.g. from Sanesecurity_, URLhaus_ and others.
Fangfrisch was designed with security in mind, to be run by an unprivileged user only.

%package bin
Summary: bin components for the fangfrisch package.
Group: Binaries

%description bin
bin components for the fangfrisch package.


%package python
Summary: python components for the fangfrisch package.
Group: Default
Requires: fangfrisch-python3 = %{version}-%{release}

%description python
python components for the fangfrisch package.


%package python3
Summary: python3 components for the fangfrisch package.
Group: Default
Requires: python3-core
Provides: pypi(fangfrisch)
Requires: pypi(sqlalchemy)
Requires: pypi(requests)

%description python3
python3 components for the fangfrisch package.


%prep
%setup -q -n fangfrisch-1.2.0
cd %{_builddir}/fangfrisch-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586214966
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fangfrisch

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
